# Generated by Django 5.1 on 2024-09-02 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('member_since', models.DateTimeField()),
                ('active_status', models.BooleanField(default=True)),
                ('tags', models.JSONField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Circle User',
                'verbose_name_plural': 'Circle Users',
            },
        ),
        migrations.CreateModel(
            name='HotmartSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_id', models.IntegerField()),
                ('recurrency_period', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('product_ucode', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=10)),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscriber_name', models.CharField(max_length=255)),
                ('subscriber_ucode', models.CharField(max_length=50)),
                ('subscriber_email', models.EmailField(max_length=254)),
                ('next_billing_date', models.DateTimeField()),
                ('reference_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Hotmart Subscription',
                'verbose_name_plural': 'Hotmart Subscriptions',
            },
        ),
    ]
