# Generated by Django 5.1 on 2024-09-02 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_circleuser_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
