# Generated by Django 5.1 on 2024-09-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_circleuser_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='member_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
